FROM alpine:latest

RUN apk update && \
    apk add tar && \
    apk add vim && \
    apk add gzip && \
    apk add openjdk11 && \
	apk add maven && \
	apk add git && \
	apk add mc && \
	apk add wget && \
	apk add curl
  
CMD ["/bin/sh"]
